//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addmin_Table
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Product_Name { get; set; }
        public string Payed_Installment { get; set; }
        public string C_Remaning_Installment { get; set; }
    }
}
