//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User_Table
    {
        public int id { get; set; }
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "Enter Mininmum 5or Max 10 letter")]

        public string Name { get; set; }
        [Display(Name = "Father Name")]
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
        [StringLength(10, MinimumLength = 5, ErrorMessage = "Enter Mininmum 5or Max 10 letter")]
        public string Father_Name { get; set; }
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "Enter Your Full CNIC Number without(-)")]
        public string CNIC { get; set; }
        [Display(Name = "Current Address")]
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
      
        public string Current_Address { get; set; }
        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
        [StringLength(13, MinimumLength = 5, ErrorMessage = "Enter Desire Product(Like Laptop,Mobile)")]
        public string Product_Name { get; set; }
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "You Cann't leave it Empty.")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Enter Your Phone Number")]
        public string Phone_Number { get; set; }
    }
}
